CREATE TABLE `trade_journal` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`instrument` varchar(32) NOT NULL,
	`tradeType` enum('CALL_BUY','PUT_BUY','CALL_SELL','PUT_SELL') NOT NULL,
	`strike` float NOT NULL,
	`entryPrice` float NOT NULL,
	`exitPrice` float,
	`quantity` int NOT NULL DEFAULT 1,
	`stopLoss` float,
	`target` float,
	`pnl` float,
	`pnlPercent` float,
	`status` enum('OPEN','CLOSED','CANCELLED') NOT NULL DEFAULT 'OPEN',
	`mode` enum('LIVE','PAPER') NOT NULL DEFAULT 'PAPER',
	`rationale` text,
	`exitReason` text,
	`tags` text,
	`aiDecision` varchar(16),
	`aiConfidence` float,
	`checklistScore` int,
	`entryTime` bigint NOT NULL,
	`exitTime` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trade_journal_id` PRIMARY KEY(`id`)
);
