@echo off
REM Auto-generated by install-scheduled-tasks.ps1 -- do not edit.
REM Mon-Fri + market-holiday guard, then chain into start-all.bat.

setlocal EnableDelayedExpansion

REM Resolve project root so the holiday check can find python_modules\.
set "ROOT=%~dp0..\"
cd /d "%ROOT%"

REM Signal to start-all.bat (and friends) that we're running under Task
REM Scheduler with no interactive console: skip any `pause` prompts so
REM error paths exit cleanly instead of hanging until ExecutionTimeLimit.
set LUBAS_HEADLESS=1

REM --- Weekday guard ---
for /f %%D in ('powershell -NoProfile -Command "(Get-Date).DayOfWeek.value__"') do set DOW=%%D
REM DayOfWeek: 0=Sun, 1=Mon, ..., 6=Sat
if "%DOW%"=="0" (
    echo [%date% %time%] Sunday -- skipping Lubas startup.
    powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0_emit-lifecycle.ps1" -Event skip -Result weekend >nul 2>&1
    exit /b 0
)
if "%DOW%"=="6" (
    echo [%date% %time%] Saturday -- skipping Lubas startup.
    powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0_emit-lifecycle.ps1" -Event skip -Result weekend >nul 2>&1
    exit /b 0
)

REM --- Holiday guard ---
REM Skip if today is a published NSE/MCX trading holiday.
REM If Python isn't available we silently skip the pre-check -- start-all.bat
REM will fail loudly on its own Python check and the failure is logged there.
call "%~dp0_detect-python.bat"
if not errorlevel 1 (
    "%PYTHON_CMD%" python_modules\market_calendar.py
    if !errorlevel! equ 1 (
        echo [%date% %time%] Market holiday -- skipping Lubas startup.
        powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0_emit-lifecycle.ps1" -Event skip -Result holiday >nul 2>&1
        exit /b 0
    )
)

call "%~dp0start-all.bat" %*
