@echo off
REM Auto-generated by install-scheduled-tasks.ps1 -- do not edit.
REM Mon-Fri only guard, then chain into start-all.bat.

for /f %%D in ('powershell -NoProfile -Command "(Get-Date).DayOfWeek.value__"') do set DOW=%%D
REM DayOfWeek: 0=Sun, 1=Mon, ..., 6=Sat
if "%DOW%"=="0" (
    echo [%date% %time%] Sunday -- skipping ATS startup.
    exit /b 0
)
if "%DOW%"=="6" (
    echo [%date% %time%] Saturday -- skipping ATS startup.
    exit /b 0
)

call "C:\Users\Admin\ai-development\ai-development\startup\start-all.bat" %*
