#requires -Version 5.1
#requires -RunAsAdministrator
<#
  Lubas -- Register Task Scheduler entries for automated daily run.

  Tasks created:
    Lubas-Startup           At log on of the current user, Mon-Fri only
                            -> runs startup\start-all.bat
    Lubas-Shutdown          Daily at 00:00
                            -> runs startup\stop-all.ps1 (graceful stop + shutdown /s)
    Lubas-Shutdown-Warning  Daily at 23:55
                            -> msg.exe popup 5 min before shutdown
    Lubas-Retrain-Saturday  Weekly Sat 02:00 (T27 + T42-FU1)
                            -> runs scripts\retrain_v2.bat (MTA for all 4 instruments
                               + saturday_promote.py auto-LATEST gate w/ Telegram alert)

  Power-on at 08:55 Mon-Fri must be set in your motherboard BIOS
  ("Resume by RTC Alarm" / "Wake on RTC"). Windows cannot boot a
  fully powered-off PC; Task Scheduler runs after Windows is up.

  Auto-login must also be enabled in `netplwiz` so the system reaches
  the desktop without manual sign-in after the BIOS-triggered boot.

  Saturday retrain wakes the machine at 02:00 via -WakeToRun. The
  machine remains awake for the duration of the retrain (~5 min today
  at Day 4 of accumulation; ~5 hrs at Day 30+ once real retrains fire).
  After the task ends, the shutdown is NOT auto-triggered -- the user
  decides when to power off on weekends.

  Run this script ONCE from an elevated PowerShell:
      powershell -ExecutionPolicy Bypass -File startup\install-scheduled-tasks.ps1

  Re-running is safe -- existing tasks are replaced.
#>

$ErrorActionPreference = 'Stop'

$root        = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$startBat    = Join-Path $root 'startup\start-all.bat'
$stopPs1     = Join-Path $root 'startup\stop-all.ps1'
$helperPs1   = Join-Path $root 'startup\_send-ctrlc-helper.ps1'

# stop-all.ps1 invokes _send-ctrlc-helper.ps1 at runtime for the graceful
# Ctrl+C path; if the helper is missing, the daily shutdown silently
# force-kills every TFA without giving them a chance to flush their NDJSON
# buffers -- data corruption risk. Fail loudly at install time.
foreach ($f in @($startBat, $stopPs1, $helperPs1)) {
    if (-not (Test-Path $f)) { throw "Required file not found: $f" }
}

$user = "$env:USERDOMAIN\$env:USERNAME"
Write-Host "Project root  : $root"
Write-Host "Run-as user   : $user"
Write-Host ""

# Common settings: don't run on battery, allow start on demand, wake the
# computer is irrelevant here (we cold-boot from BIOS), restart on failure.
$commonSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 16)

# ============================================================
#  Lubas-Startup -- At log on, Mon-Fri only
# ============================================================
$startAction = New-ScheduledTaskAction `
    -Execute 'cmd.exe' `
    -Argument "/c `"$startBat`"" `
    -WorkingDirectory $root

# Logon trigger with a Mon-Fri day-of-week filter is not directly expressible,
# so we use 5 weekly triggers all firing on logon-day for the relevant weekday.
# Simpler approach: single logon trigger; start-all.bat itself short-circuits
# on Sat/Sun by checking the day. We add that guard below as a wrapper.
$startTrigger = New-ScheduledTaskTrigger -AtLogOn -User $user

# Wrap start-all.bat so it no-ops on weekends.
$wrapperPath = Join-Path $root 'startup\_scheduled-start.bat'
$wrapperBody = @"
@echo off
REM Auto-generated by install-scheduled-tasks.ps1 -- do not edit.
REM Mon-Fri + market-holiday guard, then chain into start-all.bat.

setlocal EnableDelayedExpansion

REM Resolve project root so the holiday check can find python_modules\.
set "ROOT=%~dp0..\"
cd /d "%ROOT%"

REM Signal to start-all.bat (and friends) that we're running under Task
REM Scheduler with no interactive console: skip any `pause` prompts so
REM error paths exit cleanly instead of hanging until ExecutionTimeLimit.
set LUBAS_HEADLESS=1

REM --- Weekday guard ---
for /f %%D in ('powershell -NoProfile -Command "(Get-Date).DayOfWeek.value__"') do set DOW=%%D
REM DayOfWeek: 0=Sun, 1=Mon, ..., 6=Sat
if "%DOW%"=="0" (
    echo [%date% %time%] Sunday -- skipping Lubas startup.
    powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0_emit-lifecycle.ps1" -Event skip -Result weekend >nul 2>&1
    exit /b 0
)
if "%DOW%"=="6" (
    echo [%date% %time%] Saturday -- skipping Lubas startup.
    powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0_emit-lifecycle.ps1" -Event skip -Result weekend >nul 2>&1
    exit /b 0
)

REM --- Holiday guard ---
REM Skip if today is a published NSE/MCX trading holiday.
REM If Python isn't available we silently skip the pre-check -- start-all.bat
REM will fail loudly on its own Python check and the failure is logged there.
call "%~dp0_detect-python.bat"
if not errorlevel 1 (
    "%PYTHON_CMD%" python_modules\market_calendar.py
    if !errorlevel! equ 1 (
        echo [%date% %time%] Market holiday -- skipping Lubas startup.
        powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0_emit-lifecycle.ps1" -Event skip -Result holiday >nul 2>&1
        exit /b 0
    )
)

call "%~dp0start-all.bat" %*
"@
Set-Content -Path $wrapperPath -Value $wrapperBody -Encoding ASCII
Write-Host "Wrote weekday-guard wrapper: $wrapperPath"

$startAction = New-ScheduledTaskAction `
    -Execute 'cmd.exe' `
    -Argument "/c `"$wrapperPath`"" `
    -WorkingDirectory $root

Register-ScheduledTask `
    -TaskName 'Lubas-Startup' `
    -Action   $startAction `
    -Trigger  $startTrigger `
    -Settings $commonSettings `
    -RunLevel Limited `
    -User     $user `
    -Description 'Starts Lubas API server + 4 TFA recorders at logon (Mon-Fri).' `
    -Force | Out-Null
Write-Host "Registered: Lubas-Startup  (logon trigger, weekday-guarded)"

# ============================================================
#  Lubas-Shutdown -- Daily 00:00, graceful stop + shutdown /s
# ============================================================
$stopAction = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$stopPs1`"" `
    -WorkingDirectory $root

$stopTrigger = New-ScheduledTaskTrigger -Daily -At '00:00'

# Distinct settings: no StartWhenAvailable. We never want to "catch up"
# on a missed midnight shutdown -- if the PC was off, do nothing.
$stopSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

# Run as the current user (same session as the python recorders) with
# elevated rights -- SYSTEM can't AttachConsole across sessions, so the
# graceful Ctrl+C path requires same-session execution.
Register-ScheduledTask `
    -TaskName  'Lubas-Shutdown' `
    -Action    $stopAction `
    -Trigger   $stopTrigger `
    -Settings  $stopSettings `
    -User      $user `
    -RunLevel  Highest `
    -Description 'Graceful Lubas stop + OS shutdown at 00:00 (no catch-up on missed runs).' `
    -Force | Out-Null
Write-Host "Registered: Lubas-Shutdown (daily 00:00 as $user, elevated, no catch-up)"

# ============================================================
#  Lubas-Shutdown-Warning -- Daily 23:55, 5-minute heads-up popup
# ============================================================
# msg.exe sends a popup to the interactive session. The single 60-second
# toast at 00:00 is easy to miss when heads-down; this gives the user a
# 5-minute window to wrap up before shutdown begins, or to disable the
# Shutdown task entirely for the night (Disable-ScheduledTask 'Lubas-Shutdown').
$warnArgument = "$env:USERNAME `"Lubas will shut down in 5 minutes (00:00). Run 'shutdown /a' within 60s after the shutdown begins, or Disable-ScheduledTask 'Lubas-Shutdown' to skip it entirely tonight.`""
$warnAction = New-ScheduledTaskAction `
    -Execute 'msg.exe' `
    -Argument $warnArgument

$warnTrigger = New-ScheduledTaskTrigger -Daily -At '23:55'

# Same "no catch-up" policy: a missed warning is fine, don't surprise the
# user mid-morning with a stale popup.
$warnSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

Register-ScheduledTask `
    -TaskName  'Lubas-Shutdown-Warning' `
    -Action    $warnAction `
    -Trigger   $warnTrigger `
    -Settings  $warnSettings `
    -User      $user `
    -RunLevel  Limited `
    -Description '5-minute heads-up popup before the daily Lubas shutdown at 00:00.' `
    -Force | Out-Null
Write-Host "Registered: Lubas-Shutdown-Warning (daily 23:55 as $user)"

# ============================================================
#  Lubas-Retrain-Saturday -- Weekly Sat 02:00 (T27, V2 §6.1)
# ============================================================
# Saturday retrain runs scripts\retrain_v2.bat which loops MTA over
# all 4 instruments sequentially, then chains scripts\saturday_promote.py
# (T42-FU1) to compare each new bundle's sim_pnl vs current LATEST and
# auto-promote on PASS (V2 §2.3.4: candidate_total >= baseline x 1.20
# AND per-trade expectancy >= Rs 8). FAIL/SKIP fires a yow-partha
# Telegram alert; silence is success. Wakes the machine at 02:00 (per
# -WakeToRun) and runs as the same user that owns the parquet data.
# Today's data is too thin for a real retrain (Day 4 of accumulation),
# so this fires in v0-stopgap mode -- bundles produce SKIP verdicts
# (zero sim_pnl signals on thin data) until Day 30+ -- matches
# V2_MASTER_SPEC D76.
$retrainBat = Join-Path $root 'scripts\retrain_v2.bat'
if (-not (Test-Path $retrainBat)) { throw "Required file not found: $retrainBat" }

$retrainAction = New-ScheduledTaskAction `
    -Execute 'cmd.exe' `
    -Argument "/c `"$retrainBat`"" `
    -WorkingDirectory $root

$retrainTrigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Saturday -At '02:00'

# Retrain can run for hours once real training kicks in (~5 hrs at Day 30
# per spec budget of 19 hrs across 4 instruments × 5 folds, /4 = ~5/inst).
# Allow up to 16 hours. StartWhenAvailable so a missed Saturday catches
# up the moment the machine is on again.
$retrainSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -WakeToRun `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 16)

Register-ScheduledTask `
    -TaskName  'Lubas-Retrain-Saturday' `
    -Action    $retrainAction `
    -Trigger   $retrainTrigger `
    -Settings  $retrainSettings `
    -User      $user `
    -RunLevel  Limited `
    -Description 'Weekly Saturday MTA retrain across all 4 instruments + auto-promotion gate (T27 + T42-FU1, V2_MASTER_SPEC §6.1 + §2.3.4).' `
    -Force | Out-Null
Write-Host "Registered: Lubas-Retrain-Saturday (weekly Sat 02:00 as $user, wakes machine)"

# ============================================================
#  Lubas-SubscriptionAlert-Daily -- Daily 09:00, Dhan auto-pay reminder
# ============================================================
# Runs startup\subscription-alert.bat which checks config\subscriptions.json
# and, in the lead-time window before each account's monthly renewal day,
# logs a console warning AND sends a yow-partha Telegram alert to keep enough
# balance in the auto-pay bank. Runs EVERY day (incl. weekends/holidays) so a
# renewal on a non-trading day isn't missed; StartWhenAvailable catches up a
# missed run when the machine next powers on. Telegram is de-duped to once per
# account per day, so this never double-sends with the in-server scheduler.
$subAlertBat = Join-Path $root 'startup\subscription-alert.bat'
if (-not (Test-Path $subAlertBat)) { throw "Required file not found: $subAlertBat" }

$subAlertAction = New-ScheduledTaskAction `
    -Execute 'cmd.exe' `
    -Argument "/c `"$subAlertBat`"" `
    -WorkingDirectory $root

$subAlertTrigger = New-ScheduledTaskTrigger -Daily -At '09:00'

$subAlertSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

Register-ScheduledTask `
    -TaskName  'Lubas-SubscriptionAlert-Daily' `
    -Action    $subAlertAction `
    -Trigger   $subAlertTrigger `
    -Settings  $subAlertSettings `
    -User      $user `
    -RunLevel  Limited `
    -Description 'Daily Dhan Data API auto-pay reminder (console + yow-partha bot) before each account renewal day.' `
    -Force | Out-Null
Write-Host "Registered: Lubas-SubscriptionAlert-Daily (daily 09:00 as $user)"

Write-Host ""
Write-Host "Done. Verify all five tasks registered:"
Write-Host "  Get-ScheduledTask -TaskName 'Lubas-*' | Select TaskName,State"
Write-Host ""
Write-Host "Verify the 23:55 popup works in this session (will fire msg.exe now):"
Write-Host "  Start-ScheduledTask -TaskName 'Lubas-Shutdown-Warning'"
Write-Host "  (You should see a popup. If not, msg.exe may be blocked on this"
Write-Host "  Windows edition -- consider BurntToast or another notifier.)"
Write-Host ""
Write-Host "REMINDERS:"
Write-Host "  1. Set BIOS 'Resume by RTC Alarm' to 08:55 (Mon-Fri or daily)."
Write-Host "  2. Enable Windows auto-login via 'netplwiz' so the desktop comes up unattended."
Write-Host "  3. Test once manually:  Start-ScheduledTask -TaskName 'Lubas-Startup'"
