#requires -Version 5.1
#requires -RunAsAdministrator
<#
  ATS -- Register Task Scheduler entries for automated daily run.

  Tasks created:
    ATS-Startup   At log on of the current user, Mon-Fri only
                  -> runs startup\start-all.bat
    ATS-Shutdown  Daily at 00:00
                  -> runs startup\stop-all.ps1 (graceful stop + shutdown /s)

  Power-on at 08:55 Mon-Fri must be set in your motherboard BIOS
  ("Resume by RTC Alarm" / "Wake on RTC"). Windows cannot boot a
  fully powered-off PC; Task Scheduler runs after Windows is up.

  Auto-login must also be enabled in `netplwiz` so the system reaches
  the desktop without manual sign-in after the BIOS-triggered boot.

  Run this script ONCE from an elevated PowerShell:
      powershell -ExecutionPolicy Bypass -File startup\install-scheduled-tasks.ps1

  Re-running is safe -- existing tasks are replaced.
#>

$ErrorActionPreference = 'Stop'

$root        = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$startBat    = Join-Path $root 'startup\start-all.bat'
$stopPs1     = Join-Path $root 'startup\stop-all.ps1'

foreach ($f in @($startBat, $stopPs1)) {
    if (-not (Test-Path $f)) { throw "Required file not found: $f" }
}

$user = "$env:USERDOMAIN\$env:USERNAME"
Write-Host "Project root  : $root"
Write-Host "Run-as user   : $user"
Write-Host ""

# Common settings: don't run on battery, allow start on demand, wake the
# computer is irrelevant here (we cold-boot from BIOS), restart on failure.
$commonSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 16)

# ============================================================
#  ATS-Startup -- At log on, Mon-Fri only
# ============================================================
$startAction = New-ScheduledTaskAction `
    -Execute 'cmd.exe' `
    -Argument "/c `"$startBat`"" `
    -WorkingDirectory $root

# Logon trigger with a Mon-Fri day-of-week filter is not directly expressible,
# so we use 5 weekly triggers all firing on logon-day for the relevant weekday.
# Simpler approach: single logon trigger; start-all.bat itself short-circuits
# on Sat/Sun by checking the day. We add that guard below as a wrapper.
$startTrigger = New-ScheduledTaskTrigger -AtLogOn -User $user

# Wrap start-all.bat so it no-ops on weekends.
$wrapperPath = Join-Path $root 'startup\_scheduled-start.bat'
$wrapperBody = @"
@echo off
REM Auto-generated by install-scheduled-tasks.ps1 -- do not edit.
REM Mon-Fri only guard, then chain into start-all.bat.

for /f %%D in ('powershell -NoProfile -Command "(Get-Date).DayOfWeek.value__"') do set DOW=%%D
REM DayOfWeek: 0=Sun, 1=Mon, ..., 6=Sat
if "%DOW%"=="0" (
    echo [%date% %time%] Sunday -- skipping ATS startup.
    exit /b 0
)
if "%DOW%"=="6" (
    echo [%date% %time%] Saturday -- skipping ATS startup.
    exit /b 0
)

call "$startBat" %*
"@
Set-Content -Path $wrapperPath -Value $wrapperBody -Encoding ASCII
Write-Host "Wrote weekday-guard wrapper: $wrapperPath"

$startAction = New-ScheduledTaskAction `
    -Execute 'cmd.exe' `
    -Argument "/c `"$wrapperPath`"" `
    -WorkingDirectory $root

Register-ScheduledTask `
    -TaskName 'ATS-Startup' `
    -Action   $startAction `
    -Trigger  $startTrigger `
    -Settings $commonSettings `
    -RunLevel Limited `
    -User     $user `
    -Description 'Starts ATS API server + 4 TFA recorders at logon (Mon-Fri).' `
    -Force | Out-Null
Write-Host "Registered: ATS-Startup  (logon trigger, weekday-guarded)"

# ============================================================
#  ATS-Shutdown -- Daily 00:00, graceful stop + shutdown /s
# ============================================================
$stopAction = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$stopPs1`"" `
    -WorkingDirectory $root

$stopTrigger = New-ScheduledTaskTrigger -Daily -At '00:00'

# Distinct settings: no StartWhenAvailable. We never want to "catch up"
# on a missed midnight shutdown -- if the PC was off, do nothing.
$stopSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

# Run as the current user (same session as the python recorders) with
# elevated rights -- SYSTEM can't AttachConsole across sessions, so the
# graceful Ctrl+C path requires same-session execution.
Register-ScheduledTask `
    -TaskName  'ATS-Shutdown' `
    -Action    $stopAction `
    -Trigger   $stopTrigger `
    -Settings  $stopSettings `
    -User      $user `
    -RunLevel  Highest `
    -Description 'Graceful ATS stop + OS shutdown at 00:00 (no catch-up on missed runs).' `
    -Force | Out-Null
Write-Host "Registered: ATS-Shutdown (daily 00:00 as $user, elevated, no catch-up)"

Write-Host ""
Write-Host "Done. Verify with:  Get-ScheduledTask -TaskName 'ATS-*' | Select TaskName,State"
Write-Host ""
Write-Host "REMINDERS:"
Write-Host "  1. Set BIOS 'Resume by RTC Alarm' to 08:55 (Mon-Fri or daily)."
Write-Host "  2. Enable Windows auto-login via 'netplwiz' so the desktop comes up unattended."
Write-Host "  3. Test once manually:  Start-ScheduledTask -TaskName 'ATS-Startup'"
