#requires -Version 5.1
#requires -RunAsAdministrator
<#
  ATS -- Register Task Scheduler entries for automated daily run.

  Tasks created:
    ATS-Startup   At log on of the current user, Mon-Fri only
                  -> runs startup\start-all.bat
    ATS-Shutdown  Daily at 00:00
                  -> runs startup\stop-all.ps1 (graceful stop + shutdown /s)

  Power-on at 08:55 Mon-Fri must be set in your motherboard BIOS
  ("Resume by RTC Alarm" / "Wake on RTC"). Windows cannot boot a
  fully powered-off PC; Task Scheduler runs after Windows is up.

  Auto-login must also be enabled in `netplwiz` so the system reaches
  the desktop without manual sign-in after the BIOS-triggered boot.

  Run this script ONCE from an elevated PowerShell:
      powershell -ExecutionPolicy Bypass -File startup\install-scheduled-tasks.ps1

  Re-running is safe -- existing tasks are replaced.
#>

$ErrorActionPreference = 'Stop'

$root        = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$startBat    = Join-Path $root 'startup\start-all.bat'
$stopPs1     = Join-Path $root 'startup\stop-all.ps1'
$helperPs1   = Join-Path $root 'startup\_send-ctrlc-helper.ps1'

# stop-all.ps1 invokes _send-ctrlc-helper.ps1 at runtime for the graceful
# Ctrl+C path; if the helper is missing, the daily shutdown silently
# force-kills every TFA without giving them a chance to flush their NDJSON
# buffers -- data corruption risk. Fail loudly at install time.
foreach ($f in @($startBat, $stopPs1, $helperPs1)) {
    if (-not (Test-Path $f)) { throw "Required file not found: $f" }
}

$user = "$env:USERDOMAIN\$env:USERNAME"
Write-Host "Project root  : $root"
Write-Host "Run-as user   : $user"
Write-Host ""

# Common settings: don't run on battery, allow start on demand, wake the
# computer is irrelevant here (we cold-boot from BIOS), restart on failure.
$commonSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 16)

# ============================================================
#  ATS-Startup -- At log on, Mon-Fri only
# ============================================================
$startAction = New-ScheduledTaskAction `
    -Execute 'cmd.exe' `
    -Argument "/c `"$startBat`"" `
    -WorkingDirectory $root

# Logon trigger with a Mon-Fri day-of-week filter is not directly expressible,
# so we use 5 weekly triggers all firing on logon-day for the relevant weekday.
# Simpler approach: single logon trigger; start-all.bat itself short-circuits
# on Sat/Sun by checking the day. We add that guard below as a wrapper.
$startTrigger = New-ScheduledTaskTrigger -AtLogOn -User $user

# Wrap start-all.bat so it no-ops on weekends.
$wrapperPath = Join-Path $root 'startup\_scheduled-start.bat'
$wrapperBody = @"
@echo off
REM Auto-generated by install-scheduled-tasks.ps1 -- do not edit.
REM Mon-Fri + market-holiday guard, then chain into start-all.bat.

setlocal EnableDelayedExpansion

REM Resolve project root so the holiday check can find python_modules\.
set "ROOT=%~dp0..\"
cd /d "%ROOT%"

REM Signal to start-all.bat (and friends) that we're running under Task
REM Scheduler with no interactive console: skip any `pause` prompts so
REM error paths exit cleanly instead of hanging until ExecutionTimeLimit.
set ATS_HEADLESS=1

REM --- Weekday guard ---
for /f %%D in ('powershell -NoProfile -Command "(Get-Date).DayOfWeek.value__"') do set DOW=%%D
REM DayOfWeek: 0=Sun, 1=Mon, ..., 6=Sat
if "%DOW%"=="0" (
    echo [%date% %time%] Sunday -- skipping ATS startup.
    exit /b 0
)
if "%DOW%"=="6" (
    echo [%date% %time%] Saturday -- skipping ATS startup.
    exit /b 0
)

REM --- Holiday guard ---
REM Skip if today is a published NSE/MCX trading holiday.
REM If Python isn't available we silently skip the pre-check -- start-all.bat
REM will fail loudly on its own Python check and the failure is logged there.
call "%~dp0_detect-python.bat"
if not errorlevel 1 (
    "%PYTHON_CMD%" python_modules\market_calendar.py
    if !errorlevel! equ 1 (
        echo [%date% %time%] Market holiday -- skipping ATS startup.
        exit /b 0
    )
)

call "%~dp0start-all.bat" %*
"@
Set-Content -Path $wrapperPath -Value $wrapperBody -Encoding ASCII
Write-Host "Wrote weekday-guard wrapper: $wrapperPath"

$startAction = New-ScheduledTaskAction `
    -Execute 'cmd.exe' `
    -Argument "/c `"$wrapperPath`"" `
    -WorkingDirectory $root

Register-ScheduledTask `
    -TaskName 'ATS-Startup' `
    -Action   $startAction `
    -Trigger  $startTrigger `
    -Settings $commonSettings `
    -RunLevel Limited `
    -User     $user `
    -Description 'Starts ATS API server + 4 TFA recorders at logon (Mon-Fri).' `
    -Force | Out-Null
Write-Host "Registered: ATS-Startup  (logon trigger, weekday-guarded)"

# ============================================================
#  ATS-Shutdown -- Daily 00:00, graceful stop + shutdown /s
# ============================================================
$stopAction = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$stopPs1`"" `
    -WorkingDirectory $root

$stopTrigger = New-ScheduledTaskTrigger -Daily -At '00:00'

# Distinct settings: no StartWhenAvailable. We never want to "catch up"
# on a missed midnight shutdown -- if the PC was off, do nothing.
$stopSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

# Run as the current user (same session as the python recorders) with
# elevated rights -- SYSTEM can't AttachConsole across sessions, so the
# graceful Ctrl+C path requires same-session execution.
Register-ScheduledTask `
    -TaskName  'ATS-Shutdown' `
    -Action    $stopAction `
    -Trigger   $stopTrigger `
    -Settings  $stopSettings `
    -User      $user `
    -RunLevel  Highest `
    -Description 'Graceful ATS stop + OS shutdown at 00:00 (no catch-up on missed runs).' `
    -Force | Out-Null
Write-Host "Registered: ATS-Shutdown (daily 00:00 as $user, elevated, no catch-up)"

# ============================================================
#  ATS-Shutdown-Warning -- Daily 23:55, 5-minute heads-up popup
# ============================================================
# msg.exe sends a popup to the interactive session. The single 60-second
# toast at 00:00 is easy to miss when heads-down; this gives the user a
# 5-minute window to wrap up before shutdown begins, or to disable the
# Shutdown task entirely for the night (Disable-ScheduledTask 'ATS-Shutdown').
$warnArgument = "$env:USERNAME `"ATS will shut down in 5 minutes (00:00). Run 'shutdown /a' within 60s after the shutdown begins, or Disable-ScheduledTask 'ATS-Shutdown' to skip it entirely tonight.`""
$warnAction = New-ScheduledTaskAction `
    -Execute 'msg.exe' `
    -Argument $warnArgument

$warnTrigger = New-ScheduledTaskTrigger -Daily -At '23:55'

# Same "no catch-up" policy: a missed warning is fine, don't surprise the
# user mid-morning with a stale popup.
$warnSettings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

Register-ScheduledTask `
    -TaskName  'ATS-Shutdown-Warning' `
    -Action    $warnAction `
    -Trigger   $warnTrigger `
    -Settings  $warnSettings `
    -User      $user `
    -RunLevel  Limited `
    -Description '5-minute heads-up popup before the daily ATS shutdown at 00:00.' `
    -Force | Out-Null
Write-Host "Registered: ATS-Shutdown-Warning (daily 23:55 as $user)"

Write-Host ""
Write-Host "Done. Verify with:  Get-ScheduledTask -TaskName 'ATS-*' | Select TaskName,State"
Write-Host ""
Write-Host "REMINDERS:"
Write-Host "  1. Set BIOS 'Resume by RTC Alarm' to 08:55 (Mon-Fri or daily)."
Write-Host "  2. Enable Windows auto-login via 'netplwiz' so the desktop comes up unattended."
Write-Host "  3. Test once manually:  Start-ScheduledTask -TaskName 'ATS-Startup'"
