/**
 * AI Decisions REST Routes
 *
 * Serves AI decision JSON files generated by the Python AI Decision Engine.
 * These files are saved to python_modules/ai_decision_<instrument>.json.
 *
 * Endpoints:
 *   GET /api/ai-decisions           — List all available AI decisions
 *   GET /api/ai-decisions/:instrument — Get a specific instrument's AI decision
 */

import { Router } from "express";
import fs from "fs";
import path from "path";

const router = Router();

const INSTRUMENTS = ["NIFTY_50", "BANKNIFTY", "CRUDEOIL", "NATURALGAS"];

// The AI decision engine saves files relative to the python_modules directory
const PYTHON_MODULES_DIR = path.resolve(__dirname, "..", "python_modules");

/**
 * Read an AI decision file for a given instrument.
 * Returns null if the file doesn't exist or is malformed.
 */
function readDecisionFile(instrument: string): Record<string, unknown> | null {
  const filePath = path.join(
    PYTHON_MODULES_DIR,
    `ai_decision_${instrument.toLowerCase()}.json`
  );

  try {
    if (!fs.existsSync(filePath)) return null;
    const raw = fs.readFileSync(filePath, "utf-8");
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

/**
 * GET /api/ai-decisions
 * Returns all available AI decisions as an array.
 */
router.get("/", (_req, res) => {
  const results = INSTRUMENTS.map((instrument) => {
    const decision = readDecisionFile(instrument);
    return {
      instrument,
      decision,
      ...(decision ? {} : { error: "No decision file found" }),
    };
  });

  res.json(results);
});

/**
 * GET /api/ai-decisions/:instrument
 * Returns a single instrument's AI decision.
 */
router.get("/:instrument", (req, res) => {
  const instrument = req.params.instrument.toUpperCase();

  if (!INSTRUMENTS.includes(instrument)) {
    res.status(400).json({
      error: `Unknown instrument: ${instrument}. Valid: ${INSTRUMENTS.join(", ")}`,
    });
    return;
  }

  const decision = readDecisionFile(instrument);

  if (!decision) {
    res.status(404).json({
      instrument,
      error: "No AI decision available. Run the AI Decision Engine first.",
    });
    return;
  }

  res.json({ instrument, decision });
});

export default router;
